server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    application:
        name: smartsearch
    data:
        cassandra:
            contactPoints: localhost
            protocolVersion: V4
            compression: LZ4
            keyspaceName: smartsearch
            repositories:
                enabled: false

logstash:
    enabled: false
    port: 8081
    host: localhost
    queueSize: 256
