server:
    port: 8888

spring:
    application:
        name: smartsearch
    data:
        cassandra:
            contactPoints: localhost
            protocolVersion: V4
            compression: LZ4
            keyspaceName: smartsearch
            repositories:
                enabled: false

logstash:
    enabled: false
    port: 8081
    host: localhost
    queueSize: 256
